export const ROLES = {
  CUSTOMER: "ROLE_CUSTOMER",
  ADMIN: "ROLE_ADMIN",
  MANAGER: "ROLE_MANAGER",
  SUPERADMIN: "ROLE_SUPER_ADMIN",
};

export const DASHBOARD_ALLOWED_ROLES = [
  ROLES.ADMIN,
  ROLES.MANAGER,
  ROLES.SUPERADMIN,
];